import type { CoffeePoint, ProductItem, Employee, SlotConfig, ShiftOrder, Waybill, LegalEntity, Workshop, Driver } from '../types/index.ts';

export const INITIAL_LEGAL_ENTITIES: LegalEntity[] = [
  {
    id: 'le-1',
    name: 'ООО «Арома Холдинг»',
    shortName: 'Арома Холдинг',
    inn: '7701984210',
    kpp: '770101001',
    ogrn: '1187746123456',
    legalAddress: '101000, г. Москва, пер. Кривоколенный, д. 9, стр. 2',
    actualAddress: '101000, г. Москва, ул. Тверская, д. 12',
    bankName: 'ПАО «Сбербанк» г. Москва',
    bik: '044525225',
    checkingAccount: '40702810438000123456',
    correspondentAccount: '30101810400000000225',
    directorName: 'Воронов Сергей Александрович',
    phone: '+7 (495) 789-01-23',
    email: 'buh@aroma-coffee.ru',
    taxSystem: 'УСН (Доходы - Расходы, 15%)',
    source: 'manual',
    external_id: '1C-ORG-001',
    archived: false,
    createdAt: '2026-01-15T08:00:00Z',
  },
  {
    id: 'le-2',
    name: 'ИП Морозова Анна Сергеевна',
    shortName: 'ИП Морозова А.С.',
    inn: '772489123045',
    kpp: '',
    ogrn: '320774600192834',
    legalAddress: '115404, г. Москва, ул. Бирюлевская, д. 18, кв. 42',
    actualAddress: '119002, г. Москва, ул. Старый Арбат, д. 28',
    bankName: 'АО «Альфа-Банк» г. Москва',
    bik: '044525593',
    checkingAccount: '40802810901400054321',
    correspondentAccount: '30101810200000000593',
    directorName: 'Морозова Анна Сергеевна',
    phone: '+7 (916) 123-45-67',
    email: 'arbat.cafe@gmail.com',
    taxSystem: 'Патент (ПСН) + УСН Доходы',
    source: 'manual',
    external_id: '1C-ORG-002',
    archived: false,
    createdAt: '2026-02-01T10:00:00Z',
  },
  {
    id: 'le-3',
    name: 'ООО «Логистик Экспресс МСК»',
    shortName: 'Логистик Экспресс',
    inn: '7721834921',
    kpp: '772101001',
    ogrn: '1197746889922',
    legalAddress: '109428, г. Москва, Рязанский проспект, д. 24, корп. 1',
    actualAddress: '109428, г. Москва, Рязанский проспект, д. 24, корп. 1',
    bankName: 'ПАО Банк «ФК Открытие»',
    bik: '044525985',
    checkingAccount: '40702810100010998877',
    correspondentAccount: '30101810845250000985',
    directorName: 'Соколов Евгений Петрович',
    phone: '+7 (495) 678-90-12',
    email: 'delivery@logistic-msk.ru',
    taxSystem: 'ОСНО (с НДС 20%)',
    source: 'manual',
    external_id: '1C-ORG-003',
    archived: false,
    createdAt: '2026-01-10T09:00:00Z',
  },
];

export const INITIAL_WORKSHOPS: Workshop[] = [
  {
    id: 'ws-1',
    name: 'Центральный кондитерский цех (Текстильщики)',
    legalEntityId: 'le-1',
    address: 'г. Москва, ул. Грайвороновская, д. 20, стр. 5',
    chiefName: 'Архипов Павел Николаевич',
    phone: '+7 (495) 321-45-67',
    capacity: '800 позиций выпечки в смену',
    source: 'manual',
    external_id: '1C-PROD-FAC-01',
    archived: false,
    createdAt: '2026-01-20T08:00:00Z',
  },
  {
    id: 'ws-2',
    name: 'Пекарня и обжарочный цех (Север)',
    legalEntityId: 'le-1',
    address: 'г. Москва, Сигнальный проезд, д. 16, стр. 3',
    chiefName: 'Белов Григорий Матвеевич',
    phone: '+7 (495) 432-56-78',
    capacity: '500 позиций + 200 кг кофе/сутки',
    source: 'manual',
    external_id: '1C-PROD-FAC-02',
    archived: false,
    createdAt: '2026-02-10T08:00:00Z',
  },
];

export const INITIAL_DRIVERS: Driver[] = [
  {
    id: 'drv-1',
    name: 'Михаил Васильев',
    phone: '+7 (915) 333-22-11',
    legalEntityId: 'le-3',
    assignedWorkshopId: 'ws-1',
    vehicleModel: 'ГАЗель NEXT (Изотерм)',
    licensePlate: 'В782ОК 777',
    hasRefrigerator: true,
    status: 'active',
    archived: false,
    createdAt: '2026-01-25T08:00:00Z',
  },
  {
    id: 'drv-2',
    name: 'Алексей Соколов',
    phone: '+7 (926) 444-55-66',
    legalEntityId: 'le-3',
    assignedWorkshopId: 'ws-1',
    vehicleModel: 'Лада Ларгус Фургон',
    licensePlate: 'У412МН 799',
    hasRefrigerator: false,
    status: 'active',
    archived: false,
    createdAt: '2026-02-05T08:00:00Z',
  },
  {
    id: 'drv-3',
    name: 'Дмитрий Новиков',
    phone: '+7 (903) 555-66-77',
    legalEntityId: 'le-1',
    assignedWorkshopId: 'ws-2',
    vehicleModel: 'Ford Transit Custom',
    licensePlate: 'Е605ТР 777',
    hasRefrigerator: true,
    status: 'on_route',
    archived: false,
    createdAt: '2026-02-15T08:00:00Z',
  },
];

export const INITIAL_POINTS: CoffeePoint[] = [
  {
    id: 'point-1',
    name: 'Кофейня №1 (Центральная)',
    address: 'ул. Тверская, 12',
    legalEntityId: 'le-1',
    assignedWorkshopId: 'ws-1',
    assignedEmployeeIds: ['emp-1'],
    source: 'manual',
    external_id: 'EXT-LOC-001',
    archived: false,
  },
  {
    id: 'point-2',
    name: 'Кофейня №2 (Арбат)',
    address: 'ул. Старый Арбат, 28',
    legalEntityId: 'le-2',
    assignedWorkshopId: 'ws-1',
    assignedEmployeeIds: ['emp-2'],
    source: 'manual',
    external_id: 'EXT-LOC-002',
    archived: false,
  },
  {
    id: 'point-3',
    name: 'Кофейня №3 (Сити)',
    address: 'Пресненская наб., 8 стр. 1',
    legalEntityId: 'le-1',
    assignedWorkshopId: 'ws-2',
    assignedEmployeeIds: ['emp-3'],
    source: 'external',
    external_id: 'EXT-LOC-003',
    archived: false,
  },
  {
    id: 'point-4',
    name: 'Кофейня №4 (Патриаршие)',
    address: 'М. Бронная, 19',
    legalEntityId: 'le-1',
    assignedWorkshopId: 'ws-1',
    assignedEmployeeIds: [],
    source: 'manual',
    external_id: 'EXT-LOC-004',
    archived: false,
  },
];

export const INITIAL_PRODUCTS: ProductItem[] = [
  // Свежая выпечка
  {
    id: 'prod-1',
    sku: 'BAKE-001',
    name: 'Круассан классический сливочный',
    unit: 'шт',
    category: 'Свежая выпечка',
    source: 'external',
    external_id: '1C-PROD-101',
    archived: false,
  },
  {
    id: 'prod-2',
    sku: 'BAKE-002',
    name: 'Круассан миндальный с франжипаном',
    unit: 'шт',
    category: 'Свежая выпечка',
    source: 'external',
    external_id: '1C-PROD-102',
    archived: false,
  },
  {
    id: 'prod-3',
    sku: 'BAKE-003',
    name: 'Улитка с корицей и глазурью',
    unit: 'шт',
    category: 'Свежая выпечка',
    source: 'manual',
    external_id: '1C-PROD-103',
    archived: false,
  },
  {
    id: 'prod-4',
    sku: 'BAKE-004',
    name: 'Даниш с лесной вишней',
    unit: 'шт',
    category: 'Свежая выпечка',
    source: 'manual',
    external_id: '1C-PROD-104',
    archived: false,
  },
  {
    id: 'prod-5',
    sku: 'BAKE-005',
    name: 'Чиабатта с вялеными томатами',
    unit: 'шт',
    category: 'Свежая выпечка',
    source: 'manual',
    external_id: '1C-PROD-105',
    archived: false,
  },

  // Кофе и чай
  {
    id: 'prod-6',
    sku: 'COF-001',
    name: 'Эспрессо бленд Бразилия / Колумбия (зерно)',
    unit: 'кг',
    category: 'Кофе и зерно',
    source: 'external',
    external_id: '1C-PROD-201',
    archived: false,
  },
  {
    id: 'prod-7',
    sku: 'COF-002',
    name: 'Спешелти Эфиопия Иргачеф (фильтр/зерно)',
    unit: 'кг',
    category: 'Кофе и зерно',
    source: 'external',
    external_id: '1C-PROD-202',
    archived: false,
  },
  {
    id: 'prod-8',
    sku: 'COF-003',
    name: 'Матча церемониальная Uji',
    unit: 'уп (250г)',
    category: 'Кофе и зерно',
    source: 'manual',
    external_id: '1C-PROD-203',
    archived: false,
  },

  // Молоко и альтернативы
  {
    id: 'prod-9',
    sku: 'MILK-001',
    name: 'Молоко коровье цельное 3.2% Barista',
    unit: 'л',
    category: 'Молоко и альтернативы',
    source: 'external',
    external_id: '1C-PROD-301',
    archived: false,
  },
  {
    id: 'prod-10',
    sku: 'MILK-002',
    name: 'Молоко овсяное Barista Edition',
    unit: 'л',
    category: 'Молоко и альтернативы',
    source: 'external',
    external_id: '1C-PROD-302',
    archived: false,
  },
  {
    id: 'prod-11',
    sku: 'MILK-003',
    name: 'Молоко кокосовое без сахара',
    unit: 'л',
    category: 'Молоко и альтернативы',
    source: 'manual',
    external_id: '1C-PROD-303',
    archived: false,
  },
  {
    id: 'prod-12',
    sku: 'MILK-004',
    name: 'Сливки питьевые 10%',
    unit: 'л',
    category: 'Молоко и альтернативы',
    source: 'manual',
    external_id: '1C-PROD-304',
    archived: false,
  },

  // Сиропы и расходники
  {
    id: 'prod-13',
    sku: 'SYR-001',
    name: 'Сироп Солёная карамель (натур.)',
    unit: 'бут (1л)',
    category: 'Сиропы и расходники',
    source: 'manual',
    external_id: '1C-PROD-401',
    archived: false,
  },
  {
    id: 'prod-14',
    sku: 'SYR-002',
    name: 'Сироп Лаванда с черникой',
    unit: 'бут (1л)',
    category: 'Сиропы и расходники',
    source: 'manual',
    external_id: '1C-PROD-402',
    archived: false,
  },
  {
    id: 'prod-15',
    sku: 'SUP-001',
    name: 'Стаканы двухслойные 300мл (крафт)',
    unit: 'туба (50шт)',
    category: 'Сиропы и расходники',
    source: 'manual',
    external_id: '1C-PROD-501',
    archived: false,
  },
  {
    id: 'prod-16',
    sku: 'SUP-002',
    name: 'Крышки черные 80мм под стакан',
    unit: 'уп (100шт)',
    category: 'Сиропы и расходники',
    source: 'manual',
    external_id: '1C-PROD-502',
    archived: false,
  },
];

export const INITIAL_EMPLOYEES: Employee[] = [
  {
    id: 'emp-1',
    name: 'Анна Морозова',
    role: 'shift_supervisor',
    pointId: 'point-1',
    phone: '+7 (916) 123-45-67',
    archived: false,
  },
  {
    id: 'emp-2',
    name: 'Дмитрий Власов',
    role: 'shift_supervisor',
    pointId: 'point-2',
    phone: '+7 (926) 234-56-78',
    archived: false,
  },
  {
    id: 'emp-3',
    name: 'Екатерина Смирнова',
    role: 'shift_supervisor',
    pointId: 'point-3',
    phone: '+7 (903) 345-67-89',
    archived: false,
  },
  {
    id: 'emp-4',
    name: 'Павел Архипов',
    role: 'production_operator',
    phone: '+7 (985) 456-78-90',
    archived: false,
  },
  {
    id: 'emp-5',
    name: 'Старший смены',
    role: 'admin',
    email: 'admin@aroma-coffee.ru',
  phone: '+7 (999) 567-89-01',
  archived: false,
  },
];

export const INITIAL_SLOTS: SlotConfig[] = [
  {
    id: 'morning',
    name: 'Утренний слот',
    deadlineTime: '07:30',
    deliveryTime: '09:00',
    description: 'Основная утренняя поставка свежей выпечки, сэндвичей и заготовок',
    isActive: true,
  },
  {
    id: 'evening',
    name: 'Вечерний слот',
    deadlineTime: '16:30',
    deliveryTime: '18:30',
    description: 'Вечерний довоз молока, кофейного зерна и расходных материалов',
    isActive: true,
  },
];

const TODAY = new Date().toISOString().split('T')[0];

export const INITIAL_ORDERS: ShiftOrder[] = [
  {
    id: 'ord-today-p2-morning',
    idempotencyKey: 'idemp-p2-morning-01',
    pointId: 'point-2',
    pointName: 'Кофейня №2 (Арбат)',
    slotId: 'morning',
    date: TODAY,
    status: 'submitted',
    createdBy: 'Дмитрий Власов',
    createdAt: `${TODAY}T06:50:00Z`,
    updatedAt: `${TODAY}T07:15:00Z`,
    submittedAt: `${TODAY}T07:15:00Z`,
    items: [
      { productId: 'prod-1', sku: 'BAKE-001', name: 'Круассан классический сливочный', unit: 'шт', category: 'Свежая выпечка', quantity: 25 },
      { productId: 'prod-2', sku: 'BAKE-002', name: 'Круассан миндальный с франжипаном', unit: 'шт', category: 'Свежая выпечка', quantity: 15 },
      { productId: 'prod-9', sku: 'MILK-001', name: 'Молоко коровье цельное 3.2% Barista', unit: 'л', category: 'Молоко и альтернативы', quantity: 30 },
      { productId: 'prod-10', sku: 'MILK-002', name: 'Молоко овсяное Barista Edition', unit: 'л', category: 'Молоко и альтернативы', quantity: 12 },
    ],
  },
  {
    id: 'ord-today-p3-morning',
    idempotencyKey: 'idemp-p3-morning-01',
    pointId: 'point-3',
    pointName: 'Кофейня №3 (Сити)',
    slotId: 'morning',
    date: TODAY,
    status: 'submitted',
    createdBy: 'Екатерина Смирнова',
    createdAt: `${TODAY}T07:05:00Z`,
    updatedAt: `${TODAY}T07:22:00Z`,
    submittedAt: `${TODAY}T07:22:00Z`,
    items: [
      { productId: 'prod-1', sku: 'BAKE-001', name: 'Круассан классический сливочный', unit: 'шт', category: 'Свежая выпечка', quantity: 40 },
      { productId: 'prod-3', sku: 'BAKE-003', name: 'Улитка с корицей и глазурью', unit: 'шт', category: 'Свежая выпечка', quantity: 20 },
      { productId: 'prod-6', sku: 'COF-001', name: 'Эспрессо бленд Бразилия / Колумбия (зерно)', unit: 'кг', category: 'Кофе и зерно', quantity: 5 },
      { productId: 'prod-9', sku: 'MILK-001', name: 'Молоко коровье цельное 3.2% Barista', unit: 'л', category: 'Молоко и альтернативы', quantity: 40 },
    ],
  },
];

export const INITIAL_WAYBILLS: Waybill[] = [
  {
    id: 'WB-SAMPLE-01',
    orderId: 'ord-today-p2-morning',
    pointId: 'point-2',
    pointName: 'Кофейня №2 (Арбат)',
    date: TODAY,
    slotId: 'morning',
    status: 'dispatched',
    driverName: 'Михаил (Газель в782ок)',
    createdAt: `${TODAY}T07:45:00Z`,
    dispatchedAt: `${TODAY}T08:15:00Z`,
    dispatchedBy: 'Павел Архипов',
    items: [
      {
        productId: 'prod-1',
        sku: 'BAKE-001',
        productName: 'Круассан классический сливочный',
        unit: 'шт',
        category: 'Свежая выпечка',
        orderedQuantity: 25,
        dispatchedQuantity: 20,
        dispatchDiscrepancyReason: 'Брак при выпечке утренней партии (недопек)',
      },
      {
        productId: 'prod-2',
        sku: 'BAKE-002',
        productName: 'Круассан миндальный с франжипаном',
        unit: 'шт',
        category: 'Свежая выпечка',
        orderedQuantity: 15,
        dispatchedQuantity: 15,
      },
      {
        productId: 'prod-9',
        sku: 'MILK-001',
        productName: 'Молоко коровье цельное 3.2% Barista',
        unit: 'л',
        category: 'Молоко и альтернативы',
        orderedQuantity: 30,
        dispatchedQuantity: 30,
      },
      {
        productId: 'prod-10',
        sku: 'MILK-002',
        productName: 'Молоко овсяное Barista Edition',
        unit: 'л',
        category: 'Молоко и альтернативы',
        orderedQuantity: 12,
        dispatchedQuantity: 12,
      },
    ],
  },
];
